### PR TITLE
Adding new DateTime extensions.

### PR DESCRIPTION
**Pull request by Daeer-Projects**
Added two new extension methods for the System.DateTime object.

- ShouldBeWithinRangeOf
- Between

Added new unit tests for the extensions.
Updated the ReadMe to show details and examples.
I apologise if something goes wrong, as this is my first "pull request!"

### CODE REVIEW

**Comment by Daeer-Projects** [comment]
Hello,
I've merged the changes set up for the different frameworks, and ran the unit tests.  All passed locally before committing.  The build looks like it works as well.  So, good sign there.

I've fix some minor spelling mistakes in the ReadMe file as well.

I did notice, that the framework updates haven't been applied to the test project.  Was this intentional?
I hope the code is OK for you.

**Comment by Tazmainiandevil** [comment]
ShouldBeWithinRangeOf - What happens if seconds range is a negative number? Perhaps create a test for that and then look at safe guarding if necessary

**Comment by Tazmainiandevil** [comment]
The framework updates in the test project are missed intentionally as they are .NET Standard which cannot be unit tested as xunit can only test frameworks.

**Comment by Tazmainiandevil** [comment]
I'll merge this in but not create a new version until the ShouldBeWithinRangeOf negative number is dealt with.

**Pull request merged**
